/logging/sim:
  ros__parameters:
    log_level: debug
    log_file: /tmp/sim.log
    log_format: '[%(name)s] [%(levelname)s] [%(asctime)s] [%(filename)s:%(lineno)d] %(message)s'
    log_datefmt: '%Y-%m-%d %H:%M:%S'
    log_max_size: 10000000
    log_backup_count: 5
    log_console: true
    log_file: true
    log_syslog: false
    log_syslog_facility: user
    log_syslog_address: /dev/log
    log_syslog_port: 514
    log_syslog_protocol: udp
    log_syslog_prefix: ''
    log_syslog_suffix: ''
    log_syslog_ident: ''
    log_syslog_log_level: debug
    log_syslog_log_format: '[%(name)s] [%(levelname)s] [%(asctime)s] [%(filename)s:%(lineno)d] %(message)s'
    log_syslog_log_datefmt: '%Y-%m-%d %H:%M:%S'
    log_syslog_log_max_size: 10000000
    log_syslog_log_backup_count: 5
    log_syslog_log_console: false
    log_syslog_log_file: false
    log_syslog_log_syslog: true
    log_syslog_log_syslog_facility: user
    log_syslog_log_syslog_address: /dev/log
    log_syslog_log_syslog_port: 514
    log_syslog_log_syslog_protocol: udp
    log_syslog_log_syslog_prefix: ''
    log_syslog_log_syslog_suffix: ''
    log_syslog_log_syslog_ident: ''
    log_syslog_log_syslog_log_level: debug
    log_syslog_log_syslog_log_format: '[%(name)s] [%(levelname)s] [%(asctime)s] [%(filename)s:%(lineno)d] %(message)s'
    log_syslog_log_syslog_log_datefmt: '%Y-%m-%d %H:%M:%S'
    log_syslog_log_syslog_log_max_size: 10000000
    log_syslog_log_syslog_log_backup_count: 5
    log_syslog_log_syslog_log_console: false
    log_syslog_log_syslog_log_file: false
    log_syslog_log_syslog_log_syslog: true