/rbsim/sim:
  ros__parameters:
    freqsim: 100.0  # refresh rate of sim loop
    h: 0.01         # time step
    g_p: [0.0, 0.0, 1.0]  # starting position of drone
    l: 0.3535          # length of drone
    w: 0.3535          # width of drone
    he: 0.306          # height of drone
    In: [0.02166666666666667, 0.0, 0.0,
        0.0, 0.02166666666666667, 0.0,
        0.0, 0.0, 0.04000000000000001]  # inertia matrix
    mass: 1.5       # mass of drone
    con_rad: 0.5    # radius of drone
    prop_dia: 0.254   # diameter of propeller
    kprop: 0.0000012843          # prop k value will need to divide by 1.2*prop_dia^4
    bprop: 0.0000000180137       # prop b value will need to divide by 1.2*prop_dia^5
    xypdis: 0.177     # xy position of propellers
    zpdis: 0.0933      # z position of propellers
    Tscale: 1       # scale of thrust
    PIDlims: [220.0, 220.0, 200.0, 
              0.3, 0.3, 0.3, 
              12.0, 3.0, 1.5, 
              6.27, 52.27, 45.0, 
              15.68]  # PID limits, first 3 will need to be converted from deg to rads
    kp: [1.25, 1.25, 4.47]  # proportional gains
    kvp: [2.72, 2.7, 7.56]  # proportional velocity gains
    kvi: [1.08, 1.07, 1.74]  # integral velocity gains
    kvd: [0.56, -0.33, 0.45]  # derivative velocity gains
    kap: [6.0, 6.0, 2.5]  # proportional acceleration gains
    krp: [0.262, 0.303, 0.309]  # proportional rate gains
    kri: [0.254, 0.305, 0.304]  # integral rate gains
    krd: [-0.015, 0.0026, 0.0006]  # derivative rate gains
    krff: [-0.002, -0.01, 0.004]  # feedforward rate gains
    vel_con_lims: [1.0, 1.0]  # velocity limits
    n: [-1.0, 0.0, 0.0,
        1.0, 0.0, 0.0,
        0.0, -1.0, 0.0,
        0.0, 1.0, 0.0,
        0.0, 0.0, -1.0,
        0.0, 0.0, 1.0]  # normal vectors
    nhat: [-1.0, 0.0, 0.0,
        1.0, 0.0, 0.0,
        0.0, -1.0, 0.0,
        0.0, 1.0, 0.0,
        0.0, 0.0, -1.0,
        0.0, 0.0, 1.0]  # normal unit vectors
    poswall: 5.0 # position of wall
    negwall: -5.0 # position of wall
    d: [-1.0, 1.0, -1.0, 1.0, -2.0, 0.0]  # distance from origin for each wall; i1*poswall, i2*negwall, i3*poswall, i4*negwall, i5*poswall
    stiff: 100.0      # stiffness
    damp: 10.0       # damping
   